language: csharp
solution: CoreRSS.sln
dist: trusty
sudo: required

mono: none

dotnet:
  - latest
  - 1.0.1

script: dotnet restore

jobs:
  include:
    - stage: test
    - script:
      - cd ./CoreRSS.Tests
      - dotnet build
      - dotnet test
