language: csharp
solution: CoreRSS.sln
dotnet: 1.0.1
dist: trusty
sudo: required
jobs:
  include:
    - stage: build
    - script:
      - cd ./CoreRSS
      - dotnet restore
      - dotnet build
    - stage: tests
    - script: 
      - cd ./CoreRSS.Tests
      - dotnet restore
      - dotnet build
      - dotnet test
