language: csharp
solution: CoreRSS.sln
dist: trusty
sudo: required

mono: none

dotnet: 1.0.1

install: dotnet restore

script:
  - cd ./CoreRSS.Tests
  - dotnet build
  - dotnet test

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
    - dotnet: 1.1.5
      mono: none
      dist: trusty
    - dotnet: 2.0.3
      mono: none
      dist: trusty
    - mono: latest